version: "3.9"

services:
  graphql-server:
    container_name: graphql-server
    image: graphql-server:latest
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    user: root
    restart: always
    tty: true
    stdin_open: true
    command: |
      bash -c "
        npm install && \
        npm run dev:graphql
      "
    env_file:
      - .env
    ports:
      - "${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}"
    volumes:
      - .:/usr/src/app
    networks:
      - graphql-server

networks:
  graphql-server:
    name: graphql-server
    driver: bridge
