name: Docker Image Publish

on:
  release:
    types: [created]

jobs:
  docker:
    name: Publish image to Docker
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish to Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nodejs-typescript-express-server:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/nodejs-typescript-express-server:latest