ename: E2E Tests

on:
  push:
    branches: [develop]

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Run E2E tests
        run: npm run test:e2e