services:
  api-http-server-dev:
    container_name: api-http-server-dev
    image: node:lts
    restart: always
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    command: |
      sh -c "
        chmod +x ./scripts && \
        ./scripts/wait-for-it.sh $DATABASE_HOST $DATABASE_PORT && \
        npm install && \
        npm run dev:http
      "
    env_file:
      - .env
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    networks:
      - api
  database:
    container_name: database
    image: "postgres:latest"
    restart: always
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    networks:
      - api

networks:
  api:
    name: api
    driver: bridge
