version: "3.9"

services:
  http-server:
    container_name: http-server
    image: http-server:latest
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    user: root
    restart: always
    tty: true
    stdin_open: true
    command: |
      bash -c "
        chmod +x ./scripts/wait-for-it.sh && \
        ./scripts/wait-for-it.sh $DATABASE_HOST $DATABASE_PORT && \
        npm install && \
        npm run db:migrate:up && \
        npm run db:seed:run && \
        npm run dev:http
      "
    env_file:
      - .env
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresql
    networks:
      - http-server
  postgresql:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: "postgres:latest"
    restart: always
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    networks:
      - http-server

networks:
  http-server:
    name: http-server
    driver: bridge
