version: "3.9"

services:
  websocket-server:
    container_name: websocket-server
    image: websocket-server:latest
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    user: root
    restart: always
    tty: true
    stdin_open: true
    command: |
      bash -c "
        npm install && \
        npm run dev:websocket
      "
    env_file:
      - .env
    ports:
      - "${WEBSOCKET_SERVER_PORT}:${WEBSOCKET_SERVER_PORT}"
    volumes:
      - .:/usr/src/app
    networks:
      - websocket-server

networks:
  websocket-server:
    name: websocket-server
    driver: bridge
