name: Publish Release

on:
  release:
    types: [created]
    
jobs:
  publish:
    name: Publish to GitHub Packages
    if: startsWith(github.ref, 'refs/tags/') 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.NPM_TOKEN }}

      - name: Install node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Configure .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_TOKEN }}" > .npmrc
        
      - name: Update package.json with release version
        run: |
          sudo apt-get install jq
          jq ".version = \"${{ github.ref_name }}\"" package.json > temp.json
          mv temp.json package.json
          
      - name: Publish to GitHub Packages
        run: npm publish
      
      - name: Push changes to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): publish [skip ci]"
          commit_user_name: "GitHub Actions"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: main
          file_pattern: package.json
          token: ${{ secrets.NPM_TOKEN }}