name: Publish Release

on:
  release:
    types: [created]
    
jobs:
  publish:
    name: Publish to GitHub Packages
    if: startsWith(github.ref, 'refs/tags/') 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Set up git user
        uses: fregante/setup-git-user@v2

      - name: Configure .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_TOKEN }}" > .npmrc
        
      - name: Update package.json with release version
        run: |
          sudo apt-get install jq
          RELEASE_VERSION=${{ steps.get_release_version.outputs.RELEASE_VERSION }}
          jq ".version = \"${RELEASE_VERSION}\"" package.json > temp.json
          mv temp.json package.json
          echo "Updated package.json with release version: ${RELEASE_VERSION}"
          
      # - name: Publish to GitHub Packages
      #   run: npm publish
      
      - name: Push changes to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): publish [skip ci]"